main: net.tfminecraft.trialrooms.TrialRooms
api-version: 1.20
name: TrialRooms
version: 1.0
author: Drefvelin

depend: [MythicMobs, TLibs, DenarEconomy]

commands:
  tr:
    useage: /<command>
    description: TrialRooms Command