main: net.tfminecraft.trialrooms.TrialRooms
api-version: '1.21.10'
name: TrialRooms
version: '${project.version}'
author: Drefvelin

depend: [MythicMobs, TLibs, DenarEconomy]

commands:
  tr:
    usage: /<command>
    description: TrialRooms Command